// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AsinsInfo           string
	BuffaloProducts     string
	Favoriteproduct     string
	IkebeProduct        string
	Inactivestock       string
	KeepaProducts       string
	MWSProducts         string
	NetseaProducts      string
	NetseaShops         string
	Pc4uProducts        string
	ProductMaster       string
	RakutenProducts     string
	SpapiFees           string
	SpapiPrices         string
	Stock               string
	SuperProductDetails string
	SuperProducts       string
	SuperShops          string
}{
	AsinsInfo:           "asins_info",
	BuffaloProducts:     "buffalo_products",
	Favoriteproduct:     "favoriteproduct",
	IkebeProduct:        "ikebe_product",
	Inactivestock:       "inactivestock",
	KeepaProducts:       "keepa_products",
	MWSProducts:         "mws_products",
	NetseaProducts:      "netsea_products",
	NetseaShops:         "netsea_shops",
	Pc4uProducts:        "pc4u_products",
	ProductMaster:       "product_master",
	RakutenProducts:     "rakuten_products",
	SpapiFees:           "spapi_fees",
	SpapiPrices:         "spapi_prices",
	Stock:               "stock",
	SuperProductDetails: "super_product_details",
	SuperProducts:       "super_products",
	SuperShops:          "super_shops",
}
