// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFavoriteproducts(t *testing.T) {
	t.Parallel()

	query := Favoriteproducts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFavoriteproductsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFavoriteproductsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Favoriteproducts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFavoriteproductsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FavoriteproductSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFavoriteproductsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FavoriteproductExists(ctx, tx, o.URL, o.Jan)
	if err != nil {
		t.Errorf("Unable to check if Favoriteproduct exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FavoriteproductExists to return true, but got false.")
	}
}

func testFavoriteproductsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	favoriteproductFound, err := FindFavoriteproduct(ctx, tx, o.URL, o.Jan)
	if err != nil {
		t.Error(err)
	}

	if favoriteproductFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFavoriteproductsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Favoriteproducts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFavoriteproductsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Favoriteproducts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFavoriteproductsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	favoriteproductOne := &Favoriteproduct{}
	favoriteproductTwo := &Favoriteproduct{}
	if err = randomize.Struct(seed, favoriteproductOne, favoriteproductDBTypes, false, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}
	if err = randomize.Struct(seed, favoriteproductTwo, favoriteproductDBTypes, false, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = favoriteproductOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = favoriteproductTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Favoriteproducts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFavoriteproductsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	favoriteproductOne := &Favoriteproduct{}
	favoriteproductTwo := &Favoriteproduct{}
	if err = randomize.Struct(seed, favoriteproductOne, favoriteproductDBTypes, false, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}
	if err = randomize.Struct(seed, favoriteproductTwo, favoriteproductDBTypes, false, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = favoriteproductOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = favoriteproductTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func favoriteproductBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func favoriteproductAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Favoriteproduct) error {
	*o = Favoriteproduct{}
	return nil
}

func testFavoriteproductsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Favoriteproduct{}
	o := &Favoriteproduct{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct object: %s", err)
	}

	AddFavoriteproductHook(boil.BeforeInsertHook, favoriteproductBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	favoriteproductBeforeInsertHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.AfterInsertHook, favoriteproductAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	favoriteproductAfterInsertHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.AfterSelectHook, favoriteproductAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	favoriteproductAfterSelectHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.BeforeUpdateHook, favoriteproductBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	favoriteproductBeforeUpdateHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.AfterUpdateHook, favoriteproductAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	favoriteproductAfterUpdateHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.BeforeDeleteHook, favoriteproductBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	favoriteproductBeforeDeleteHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.AfterDeleteHook, favoriteproductAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	favoriteproductAfterDeleteHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.BeforeUpsertHook, favoriteproductBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	favoriteproductBeforeUpsertHooks = []FavoriteproductHook{}

	AddFavoriteproductHook(boil.AfterUpsertHook, favoriteproductAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	favoriteproductAfterUpsertHooks = []FavoriteproductHook{}
}

func testFavoriteproductsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFavoriteproductsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(favoriteproductColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFavoriteproductsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFavoriteproductsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FavoriteproductSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFavoriteproductsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Favoriteproducts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	favoriteproductDBTypes = map[string]string{`URL`: `character varying`, `Jan`: `character varying`, `Cost`: `integer`}
	_                      = bytes.MinRead
)

func testFavoriteproductsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(favoriteproductPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(favoriteproductAllColumns) == len(favoriteproductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFavoriteproductsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(favoriteproductAllColumns) == len(favoriteproductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Favoriteproduct{}
	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, favoriteproductDBTypes, true, favoriteproductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(favoriteproductAllColumns, favoriteproductPrimaryKeyColumns) {
		fields = favoriteproductAllColumns
	} else {
		fields = strmangle.SetComplement(
			favoriteproductAllColumns,
			favoriteproductPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FavoriteproductSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFavoriteproductsUpsert(t *testing.T) {
	t.Parallel()

	if len(favoriteproductAllColumns) == len(favoriteproductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Favoriteproduct{}
	if err = randomize.Struct(seed, &o, favoriteproductDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Favoriteproduct: %s", err)
	}

	count, err := Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, favoriteproductDBTypes, false, favoriteproductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Favoriteproduct struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Favoriteproduct: %s", err)
	}

	count, err = Favoriteproducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
