// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// IkebeProduct is an object representing the database table.
type IkebeProduct struct {
	Name        null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Jan         null.String `boil:"jan" json:"jan,omitempty" toml:"jan" yaml:"jan,omitempty"`
	Price       null.Int64  `boil:"price" json:"price,omitempty" toml:"price" yaml:"price,omitempty"`
	ShopCode    string      `boil:"shop_code" json:"shop_code" toml:"shop_code" yaml:"shop_code"`
	ProductCode string      `boil:"product_code" json:"product_code" toml:"product_code" yaml:"product_code"`
	URL         null.String `boil:"url" json:"url,omitempty" toml:"url" yaml:"url,omitempty"`

	R *ikebeProductR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L ikebeProductL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var IkebeProductColumns = struct {
	Name        string
	Jan         string
	Price       string
	ShopCode    string
	ProductCode string
	URL         string
}{
	Name:        "name",
	Jan:         "jan",
	Price:       "price",
	ShopCode:    "shop_code",
	ProductCode: "product_code",
	URL:         "url",
}

var IkebeProductTableColumns = struct {
	Name        string
	Jan         string
	Price       string
	ShopCode    string
	ProductCode string
	URL         string
}{
	Name:        "ikebe_product.name",
	Jan:         "ikebe_product.jan",
	Price:       "ikebe_product.price",
	ShopCode:    "ikebe_product.shop_code",
	ProductCode: "ikebe_product.product_code",
	URL:         "ikebe_product.url",
}

// Generated where

var IkebeProductWhere = struct {
	Name        whereHelpernull_String
	Jan         whereHelpernull_String
	Price       whereHelpernull_Int64
	ShopCode    whereHelperstring
	ProductCode whereHelperstring
	URL         whereHelpernull_String
}{
	Name:        whereHelpernull_String{field: "\"ikebe_product\".\"name\""},
	Jan:         whereHelpernull_String{field: "\"ikebe_product\".\"jan\""},
	Price:       whereHelpernull_Int64{field: "\"ikebe_product\".\"price\""},
	ShopCode:    whereHelperstring{field: "\"ikebe_product\".\"shop_code\""},
	ProductCode: whereHelperstring{field: "\"ikebe_product\".\"product_code\""},
	URL:         whereHelpernull_String{field: "\"ikebe_product\".\"url\""},
}

// IkebeProductRels is where relationship names are stored.
var IkebeProductRels = struct {
}{}

// ikebeProductR is where relationships are stored.
type ikebeProductR struct {
}

// NewStruct creates a new relationship struct
func (*ikebeProductR) NewStruct() *ikebeProductR {
	return &ikebeProductR{}
}

// ikebeProductL is where Load methods for each relationship are stored.
type ikebeProductL struct{}

var (
	ikebeProductAllColumns            = []string{"name", "jan", "price", "shop_code", "product_code", "url"}
	ikebeProductColumnsWithoutDefault = []string{"shop_code", "product_code"}
	ikebeProductColumnsWithDefault    = []string{"name", "jan", "price", "url"}
	ikebeProductPrimaryKeyColumns     = []string{"shop_code", "product_code"}
	ikebeProductGeneratedColumns      = []string{}
)

type (
	// IkebeProductSlice is an alias for a slice of pointers to IkebeProduct.
	// This should almost always be used instead of []IkebeProduct.
	IkebeProductSlice []*IkebeProduct
	// IkebeProductHook is the signature for custom IkebeProduct hook methods
	IkebeProductHook func(context.Context, boil.ContextExecutor, *IkebeProduct) error

	ikebeProductQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	ikebeProductType                 = reflect.TypeOf(&IkebeProduct{})
	ikebeProductMapping              = queries.MakeStructMapping(ikebeProductType)
	ikebeProductPrimaryKeyMapping, _ = queries.BindMapping(ikebeProductType, ikebeProductMapping, ikebeProductPrimaryKeyColumns)
	ikebeProductInsertCacheMut       sync.RWMutex
	ikebeProductInsertCache          = make(map[string]insertCache)
	ikebeProductUpdateCacheMut       sync.RWMutex
	ikebeProductUpdateCache          = make(map[string]updateCache)
	ikebeProductUpsertCacheMut       sync.RWMutex
	ikebeProductUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var ikebeProductAfterSelectHooks []IkebeProductHook

var ikebeProductBeforeInsertHooks []IkebeProductHook
var ikebeProductAfterInsertHooks []IkebeProductHook

var ikebeProductBeforeUpdateHooks []IkebeProductHook
var ikebeProductAfterUpdateHooks []IkebeProductHook

var ikebeProductBeforeDeleteHooks []IkebeProductHook
var ikebeProductAfterDeleteHooks []IkebeProductHook

var ikebeProductBeforeUpsertHooks []IkebeProductHook
var ikebeProductAfterUpsertHooks []IkebeProductHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *IkebeProduct) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *IkebeProduct) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *IkebeProduct) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *IkebeProduct) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *IkebeProduct) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *IkebeProduct) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *IkebeProduct) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *IkebeProduct) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *IkebeProduct) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range ikebeProductAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddIkebeProductHook registers your hook function for all future operations.
func AddIkebeProductHook(hookPoint boil.HookPoint, ikebeProductHook IkebeProductHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		ikebeProductAfterSelectHooks = append(ikebeProductAfterSelectHooks, ikebeProductHook)
	case boil.BeforeInsertHook:
		ikebeProductBeforeInsertHooks = append(ikebeProductBeforeInsertHooks, ikebeProductHook)
	case boil.AfterInsertHook:
		ikebeProductAfterInsertHooks = append(ikebeProductAfterInsertHooks, ikebeProductHook)
	case boil.BeforeUpdateHook:
		ikebeProductBeforeUpdateHooks = append(ikebeProductBeforeUpdateHooks, ikebeProductHook)
	case boil.AfterUpdateHook:
		ikebeProductAfterUpdateHooks = append(ikebeProductAfterUpdateHooks, ikebeProductHook)
	case boil.BeforeDeleteHook:
		ikebeProductBeforeDeleteHooks = append(ikebeProductBeforeDeleteHooks, ikebeProductHook)
	case boil.AfterDeleteHook:
		ikebeProductAfterDeleteHooks = append(ikebeProductAfterDeleteHooks, ikebeProductHook)
	case boil.BeforeUpsertHook:
		ikebeProductBeforeUpsertHooks = append(ikebeProductBeforeUpsertHooks, ikebeProductHook)
	case boil.AfterUpsertHook:
		ikebeProductAfterUpsertHooks = append(ikebeProductAfterUpsertHooks, ikebeProductHook)
	}
}

// One returns a single ikebeProduct record from the query.
func (q ikebeProductQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IkebeProduct, error) {
	o := &IkebeProduct{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for ikebe_product")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all IkebeProduct records from the query.
func (q ikebeProductQuery) All(ctx context.Context, exec boil.ContextExecutor) (IkebeProductSlice, error) {
	var o []*IkebeProduct

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to IkebeProduct slice")
	}

	if len(ikebeProductAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all IkebeProduct records in the query.
func (q ikebeProductQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count ikebe_product rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q ikebeProductQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if ikebe_product exists")
	}

	return count > 0, nil
}

// IkebeProducts retrieves all the records using an executor.
func IkebeProducts(mods ...qm.QueryMod) ikebeProductQuery {
	mods = append(mods, qm.From("\"ikebe_product\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ikebe_product\".*"})
	}

	return ikebeProductQuery{q}
}

// FindIkebeProduct retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIkebeProduct(ctx context.Context, exec boil.ContextExecutor, shopCode string, productCode string, selectCols ...string) (*IkebeProduct, error) {
	ikebeProductObj := &IkebeProduct{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ikebe_product\" where \"shop_code\"=$1 AND \"product_code\"=$2", sel,
	)

	q := queries.Raw(query, shopCode, productCode)

	err := q.Bind(ctx, exec, ikebeProductObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from ikebe_product")
	}

	if err = ikebeProductObj.doAfterSelectHooks(ctx, exec); err != nil {
		return ikebeProductObj, err
	}

	return ikebeProductObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *IkebeProduct) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no ikebe_product provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(ikebeProductColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	ikebeProductInsertCacheMut.RLock()
	cache, cached := ikebeProductInsertCache[key]
	ikebeProductInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			ikebeProductAllColumns,
			ikebeProductColumnsWithDefault,
			ikebeProductColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(ikebeProductType, ikebeProductMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(ikebeProductType, ikebeProductMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ikebe_product\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ikebe_product\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into ikebe_product")
	}

	if !cached {
		ikebeProductInsertCacheMut.Lock()
		ikebeProductInsertCache[key] = cache
		ikebeProductInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the IkebeProduct.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *IkebeProduct) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	ikebeProductUpdateCacheMut.RLock()
	cache, cached := ikebeProductUpdateCache[key]
	ikebeProductUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			ikebeProductAllColumns,
			ikebeProductPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update ikebe_product, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ikebe_product\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, ikebeProductPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(ikebeProductType, ikebeProductMapping, append(wl, ikebeProductPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update ikebe_product row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for ikebe_product")
	}

	if !cached {
		ikebeProductUpdateCacheMut.Lock()
		ikebeProductUpdateCache[key] = cache
		ikebeProductUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q ikebeProductQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for ikebe_product")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for ikebe_product")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o IkebeProductSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ikebeProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ikebe_product\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, ikebeProductPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in ikebeProduct slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all ikebeProduct")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *IkebeProduct) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no ikebe_product provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(ikebeProductColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	ikebeProductUpsertCacheMut.RLock()
	cache, cached := ikebeProductUpsertCache[key]
	ikebeProductUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			ikebeProductAllColumns,
			ikebeProductColumnsWithDefault,
			ikebeProductColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			ikebeProductAllColumns,
			ikebeProductPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert ikebe_product, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(ikebeProductPrimaryKeyColumns))
			copy(conflict, ikebeProductPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ikebe_product\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(ikebeProductType, ikebeProductMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(ikebeProductType, ikebeProductMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert ikebe_product")
	}

	if !cached {
		ikebeProductUpsertCacheMut.Lock()
		ikebeProductUpsertCache[key] = cache
		ikebeProductUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single IkebeProduct record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *IkebeProduct) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no IkebeProduct provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), ikebeProductPrimaryKeyMapping)
	sql := "DELETE FROM \"ikebe_product\" WHERE \"shop_code\"=$1 AND \"product_code\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from ikebe_product")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for ikebe_product")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q ikebeProductQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no ikebeProductQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from ikebe_product")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ikebe_product")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o IkebeProductSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(ikebeProductBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ikebeProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ikebe_product\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, ikebeProductPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from ikebeProduct slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ikebe_product")
	}

	if len(ikebeProductAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *IkebeProduct) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIkebeProduct(ctx, exec, o.ShopCode, o.ProductCode)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IkebeProductSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := IkebeProductSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ikebeProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ikebe_product\".* FROM \"ikebe_product\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, ikebeProductPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in IkebeProductSlice")
	}

	*o = slice

	return nil
}

// IkebeProductExists checks if the IkebeProduct row exists.
func IkebeProductExists(ctx context.Context, exec boil.ContextExecutor, shopCode string, productCode string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ikebe_product\" where \"shop_code\"=$1 AND \"product_code\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, shopCode, productCode)
	}
	row := exec.QueryRowContext(ctx, sql, shopCode, productCode)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if ikebe_product exists")
	}

	return exists, nil
}

// Exists checks if the IkebeProduct row exists.
func (o *IkebeProduct) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return IkebeProductExists(ctx, exec, o.ShopCode, o.ProductCode)
}
