// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// NetseaProduct is an object representing the database table.
type NetseaProduct struct {
	Name        null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Jan         null.String `boil:"jan" json:"jan,omitempty" toml:"jan" yaml:"jan,omitempty"`
	Price       null.Int64  `boil:"price" json:"price,omitempty" toml:"price" yaml:"price,omitempty"`
	ShopCode    string      `boil:"shop_code" json:"shop_code" toml:"shop_code" yaml:"shop_code"`
	ProductCode string      `boil:"product_code" json:"product_code" toml:"product_code" yaml:"product_code"`
	URL         null.String `boil:"url" json:"url,omitempty" toml:"url" yaml:"url,omitempty"`

	R *netseaProductR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L netseaProductL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NetseaProductColumns = struct {
	Name        string
	Jan         string
	Price       string
	ShopCode    string
	ProductCode string
	URL         string
}{
	Name:        "name",
	Jan:         "jan",
	Price:       "price",
	ShopCode:    "shop_code",
	ProductCode: "product_code",
	URL:         "url",
}

var NetseaProductTableColumns = struct {
	Name        string
	Jan         string
	Price       string
	ShopCode    string
	ProductCode string
	URL         string
}{
	Name:        "netsea_products.name",
	Jan:         "netsea_products.jan",
	Price:       "netsea_products.price",
	ShopCode:    "netsea_products.shop_code",
	ProductCode: "netsea_products.product_code",
	URL:         "netsea_products.url",
}

// Generated where

var NetseaProductWhere = struct {
	Name        whereHelpernull_String
	Jan         whereHelpernull_String
	Price       whereHelpernull_Int64
	ShopCode    whereHelperstring
	ProductCode whereHelperstring
	URL         whereHelpernull_String
}{
	Name:        whereHelpernull_String{field: "\"netsea_products\".\"name\""},
	Jan:         whereHelpernull_String{field: "\"netsea_products\".\"jan\""},
	Price:       whereHelpernull_Int64{field: "\"netsea_products\".\"price\""},
	ShopCode:    whereHelperstring{field: "\"netsea_products\".\"shop_code\""},
	ProductCode: whereHelperstring{field: "\"netsea_products\".\"product_code\""},
	URL:         whereHelpernull_String{field: "\"netsea_products\".\"url\""},
}

// NetseaProductRels is where relationship names are stored.
var NetseaProductRels = struct {
}{}

// netseaProductR is where relationships are stored.
type netseaProductR struct {
}

// NewStruct creates a new relationship struct
func (*netseaProductR) NewStruct() *netseaProductR {
	return &netseaProductR{}
}

// netseaProductL is where Load methods for each relationship are stored.
type netseaProductL struct{}

var (
	netseaProductAllColumns            = []string{"name", "jan", "price", "shop_code", "product_code", "url"}
	netseaProductColumnsWithoutDefault = []string{"shop_code", "product_code"}
	netseaProductColumnsWithDefault    = []string{"name", "jan", "price", "url"}
	netseaProductPrimaryKeyColumns     = []string{"shop_code", "product_code"}
	netseaProductGeneratedColumns      = []string{}
)

type (
	// NetseaProductSlice is an alias for a slice of pointers to NetseaProduct.
	// This should almost always be used instead of []NetseaProduct.
	NetseaProductSlice []*NetseaProduct
	// NetseaProductHook is the signature for custom NetseaProduct hook methods
	NetseaProductHook func(context.Context, boil.ContextExecutor, *NetseaProduct) error

	netseaProductQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	netseaProductType                 = reflect.TypeOf(&NetseaProduct{})
	netseaProductMapping              = queries.MakeStructMapping(netseaProductType)
	netseaProductPrimaryKeyMapping, _ = queries.BindMapping(netseaProductType, netseaProductMapping, netseaProductPrimaryKeyColumns)
	netseaProductInsertCacheMut       sync.RWMutex
	netseaProductInsertCache          = make(map[string]insertCache)
	netseaProductUpdateCacheMut       sync.RWMutex
	netseaProductUpdateCache          = make(map[string]updateCache)
	netseaProductUpsertCacheMut       sync.RWMutex
	netseaProductUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var netseaProductAfterSelectHooks []NetseaProductHook

var netseaProductBeforeInsertHooks []NetseaProductHook
var netseaProductAfterInsertHooks []NetseaProductHook

var netseaProductBeforeUpdateHooks []NetseaProductHook
var netseaProductAfterUpdateHooks []NetseaProductHook

var netseaProductBeforeDeleteHooks []NetseaProductHook
var netseaProductAfterDeleteHooks []NetseaProductHook

var netseaProductBeforeUpsertHooks []NetseaProductHook
var netseaProductAfterUpsertHooks []NetseaProductHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *NetseaProduct) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *NetseaProduct) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *NetseaProduct) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *NetseaProduct) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *NetseaProduct) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *NetseaProduct) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *NetseaProduct) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *NetseaProduct) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *NetseaProduct) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range netseaProductAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddNetseaProductHook registers your hook function for all future operations.
func AddNetseaProductHook(hookPoint boil.HookPoint, netseaProductHook NetseaProductHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		netseaProductAfterSelectHooks = append(netseaProductAfterSelectHooks, netseaProductHook)
	case boil.BeforeInsertHook:
		netseaProductBeforeInsertHooks = append(netseaProductBeforeInsertHooks, netseaProductHook)
	case boil.AfterInsertHook:
		netseaProductAfterInsertHooks = append(netseaProductAfterInsertHooks, netseaProductHook)
	case boil.BeforeUpdateHook:
		netseaProductBeforeUpdateHooks = append(netseaProductBeforeUpdateHooks, netseaProductHook)
	case boil.AfterUpdateHook:
		netseaProductAfterUpdateHooks = append(netseaProductAfterUpdateHooks, netseaProductHook)
	case boil.BeforeDeleteHook:
		netseaProductBeforeDeleteHooks = append(netseaProductBeforeDeleteHooks, netseaProductHook)
	case boil.AfterDeleteHook:
		netseaProductAfterDeleteHooks = append(netseaProductAfterDeleteHooks, netseaProductHook)
	case boil.BeforeUpsertHook:
		netseaProductBeforeUpsertHooks = append(netseaProductBeforeUpsertHooks, netseaProductHook)
	case boil.AfterUpsertHook:
		netseaProductAfterUpsertHooks = append(netseaProductAfterUpsertHooks, netseaProductHook)
	}
}

// One returns a single netseaProduct record from the query.
func (q netseaProductQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NetseaProduct, error) {
	o := &NetseaProduct{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for netsea_products")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all NetseaProduct records from the query.
func (q netseaProductQuery) All(ctx context.Context, exec boil.ContextExecutor) (NetseaProductSlice, error) {
	var o []*NetseaProduct

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NetseaProduct slice")
	}

	if len(netseaProductAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all NetseaProduct records in the query.
func (q netseaProductQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count netsea_products rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q netseaProductQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if netsea_products exists")
	}

	return count > 0, nil
}

// NetseaProducts retrieves all the records using an executor.
func NetseaProducts(mods ...qm.QueryMod) netseaProductQuery {
	mods = append(mods, qm.From("\"netsea_products\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"netsea_products\".*"})
	}

	return netseaProductQuery{q}
}

// FindNetseaProduct retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNetseaProduct(ctx context.Context, exec boil.ContextExecutor, shopCode string, productCode string, selectCols ...string) (*NetseaProduct, error) {
	netseaProductObj := &NetseaProduct{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"netsea_products\" where \"shop_code\"=$1 AND \"product_code\"=$2", sel,
	)

	q := queries.Raw(query, shopCode, productCode)

	err := q.Bind(ctx, exec, netseaProductObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from netsea_products")
	}

	if err = netseaProductObj.doAfterSelectHooks(ctx, exec); err != nil {
		return netseaProductObj, err
	}

	return netseaProductObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NetseaProduct) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no netsea_products provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(netseaProductColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	netseaProductInsertCacheMut.RLock()
	cache, cached := netseaProductInsertCache[key]
	netseaProductInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			netseaProductAllColumns,
			netseaProductColumnsWithDefault,
			netseaProductColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(netseaProductType, netseaProductMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(netseaProductType, netseaProductMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"netsea_products\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"netsea_products\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into netsea_products")
	}

	if !cached {
		netseaProductInsertCacheMut.Lock()
		netseaProductInsertCache[key] = cache
		netseaProductInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the NetseaProduct.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NetseaProduct) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	netseaProductUpdateCacheMut.RLock()
	cache, cached := netseaProductUpdateCache[key]
	netseaProductUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			netseaProductAllColumns,
			netseaProductPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update netsea_products, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"netsea_products\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, netseaProductPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(netseaProductType, netseaProductMapping, append(wl, netseaProductPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update netsea_products row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for netsea_products")
	}

	if !cached {
		netseaProductUpdateCacheMut.Lock()
		netseaProductUpdateCache[key] = cache
		netseaProductUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q netseaProductQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for netsea_products")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for netsea_products")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NetseaProductSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), netseaProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"netsea_products\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, netseaProductPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in netseaProduct slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all netseaProduct")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NetseaProduct) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no netsea_products provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(netseaProductColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	netseaProductUpsertCacheMut.RLock()
	cache, cached := netseaProductUpsertCache[key]
	netseaProductUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			netseaProductAllColumns,
			netseaProductColumnsWithDefault,
			netseaProductColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			netseaProductAllColumns,
			netseaProductPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert netsea_products, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(netseaProductPrimaryKeyColumns))
			copy(conflict, netseaProductPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"netsea_products\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(netseaProductType, netseaProductMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(netseaProductType, netseaProductMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert netsea_products")
	}

	if !cached {
		netseaProductUpsertCacheMut.Lock()
		netseaProductUpsertCache[key] = cache
		netseaProductUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single NetseaProduct record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NetseaProduct) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NetseaProduct provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), netseaProductPrimaryKeyMapping)
	sql := "DELETE FROM \"netsea_products\" WHERE \"shop_code\"=$1 AND \"product_code\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from netsea_products")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for netsea_products")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q netseaProductQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no netseaProductQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from netsea_products")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for netsea_products")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NetseaProductSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(netseaProductBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), netseaProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"netsea_products\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, netseaProductPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from netseaProduct slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for netsea_products")
	}

	if len(netseaProductAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NetseaProduct) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNetseaProduct(ctx, exec, o.ShopCode, o.ProductCode)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NetseaProductSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NetseaProductSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), netseaProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"netsea_products\".* FROM \"netsea_products\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, netseaProductPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NetseaProductSlice")
	}

	*o = slice

	return nil
}

// NetseaProductExists checks if the NetseaProduct row exists.
func NetseaProductExists(ctx context.Context, exec boil.ContextExecutor, shopCode string, productCode string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"netsea_products\" where \"shop_code\"=$1 AND \"product_code\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, shopCode, productCode)
	}
	row := exec.QueryRowContext(ctx, sql, shopCode, productCode)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if netsea_products exists")
	}

	return exists, nil
}

// Exists checks if the NetseaProduct row exists.
func (o *NetseaProduct) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return NetseaProductExists(ctx, exec, o.ShopCode, o.ProductCode)
}
