// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSpapiPrices(t *testing.T) {
	t.Parallel()

	query := SpapiPrices()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSpapiPricesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSpapiPricesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SpapiPrices().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSpapiPricesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SpapiPriceSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSpapiPricesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SpapiPriceExists(ctx, tx, o.Asin)
	if err != nil {
		t.Errorf("Unable to check if SpapiPrice exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SpapiPriceExists to return true, but got false.")
	}
}

func testSpapiPricesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	spapiPriceFound, err := FindSpapiPrice(ctx, tx, o.Asin)
	if err != nil {
		t.Error(err)
	}

	if spapiPriceFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSpapiPricesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SpapiPrices().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSpapiPricesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SpapiPrices().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSpapiPricesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	spapiPriceOne := &SpapiPrice{}
	spapiPriceTwo := &SpapiPrice{}
	if err = randomize.Struct(seed, spapiPriceOne, spapiPriceDBTypes, false, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}
	if err = randomize.Struct(seed, spapiPriceTwo, spapiPriceDBTypes, false, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = spapiPriceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = spapiPriceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SpapiPrices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSpapiPricesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	spapiPriceOne := &SpapiPrice{}
	spapiPriceTwo := &SpapiPrice{}
	if err = randomize.Struct(seed, spapiPriceOne, spapiPriceDBTypes, false, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}
	if err = randomize.Struct(seed, spapiPriceTwo, spapiPriceDBTypes, false, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = spapiPriceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = spapiPriceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func spapiPriceBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func spapiPriceAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SpapiPrice) error {
	*o = SpapiPrice{}
	return nil
}

func testSpapiPricesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SpapiPrice{}
	o := &SpapiPrice{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SpapiPrice object: %s", err)
	}

	AddSpapiPriceHook(boil.BeforeInsertHook, spapiPriceBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	spapiPriceBeforeInsertHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.AfterInsertHook, spapiPriceAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	spapiPriceAfterInsertHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.AfterSelectHook, spapiPriceAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	spapiPriceAfterSelectHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.BeforeUpdateHook, spapiPriceBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	spapiPriceBeforeUpdateHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.AfterUpdateHook, spapiPriceAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	spapiPriceAfterUpdateHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.BeforeDeleteHook, spapiPriceBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	spapiPriceBeforeDeleteHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.AfterDeleteHook, spapiPriceAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	spapiPriceAfterDeleteHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.BeforeUpsertHook, spapiPriceBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	spapiPriceBeforeUpsertHooks = []SpapiPriceHook{}

	AddSpapiPriceHook(boil.AfterUpsertHook, spapiPriceAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	spapiPriceAfterUpsertHooks = []SpapiPriceHook{}
}

func testSpapiPricesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSpapiPricesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(spapiPriceColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSpapiPriceToOneAsinsInfoUsingAsinAsinsInfo(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SpapiPrice
	var foreign AsinsInfo

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, spapiPriceDBTypes, false, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, asinsInfoDBTypes, false, asinsInfoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AsinsInfo struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.Asin = foreign.Asin
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.AsinAsinsInfo().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.Asin != foreign.Asin {
		t.Errorf("want: %v, got %v", foreign.Asin, check.Asin)
	}

	ranAfterSelectHook := false
	AddAsinsInfoHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *AsinsInfo) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SpapiPriceSlice{&local}
	if err = local.L.LoadAsinAsinsInfo(ctx, tx, false, (*[]*SpapiPrice)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.AsinAsinsInfo == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.AsinAsinsInfo = nil
	if err = local.L.LoadAsinAsinsInfo(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.AsinAsinsInfo == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSpapiPriceToOneSetOpAsinsInfoUsingAsinAsinsInfo(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SpapiPrice
	var b, c AsinsInfo

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, spapiPriceDBTypes, false, strmangle.SetComplement(spapiPricePrimaryKeyColumns, spapiPriceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, asinsInfoDBTypes, false, strmangle.SetComplement(asinsInfoPrimaryKeyColumns, asinsInfoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, asinsInfoDBTypes, false, strmangle.SetComplement(asinsInfoPrimaryKeyColumns, asinsInfoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*AsinsInfo{&b, &c} {
		err = a.SetAsinAsinsInfo(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.AsinAsinsInfo != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AsinSpapiPrice != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.Asin != x.Asin {
			t.Error("foreign key was wrong value", a.Asin)
		}

		if exists, err := SpapiPriceExists(ctx, tx, a.Asin); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testSpapiPricesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSpapiPricesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SpapiPriceSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSpapiPricesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SpapiPrices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	spapiPriceDBTypes = map[string]string{`Asin`: `character varying`, `Price`: `bigint`, `Modified`: `date`}
	_                 = bytes.MinRead
)

func testSpapiPricesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(spapiPricePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(spapiPriceAllColumns) == len(spapiPricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSpapiPricesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(spapiPriceAllColumns) == len(spapiPricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SpapiPrice{}
	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, spapiPriceDBTypes, true, spapiPricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(spapiPriceAllColumns, spapiPricePrimaryKeyColumns) {
		fields = spapiPriceAllColumns
	} else {
		fields = strmangle.SetComplement(
			spapiPriceAllColumns,
			spapiPricePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SpapiPriceSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSpapiPricesUpsert(t *testing.T) {
	t.Parallel()

	if len(spapiPriceAllColumns) == len(spapiPricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SpapiPrice{}
	if err = randomize.Struct(seed, &o, spapiPriceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SpapiPrice: %s", err)
	}

	count, err := SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, spapiPriceDBTypes, false, spapiPricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SpapiPrice struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SpapiPrice: %s", err)
	}

	count, err = SpapiPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
