// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSuperProducts(t *testing.T) {
	t.Parallel()

	query := SuperProducts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSuperProductsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSuperProductsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SuperProducts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSuperProductsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SuperProductSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSuperProductsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SuperProductExists(ctx, tx, o.ProductCode)
	if err != nil {
		t.Errorf("Unable to check if SuperProduct exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SuperProductExists to return true, but got false.")
	}
}

func testSuperProductsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	superProductFound, err := FindSuperProduct(ctx, tx, o.ProductCode)
	if err != nil {
		t.Error(err)
	}

	if superProductFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSuperProductsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SuperProducts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSuperProductsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SuperProducts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSuperProductsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	superProductOne := &SuperProduct{}
	superProductTwo := &SuperProduct{}
	if err = randomize.Struct(seed, superProductOne, superProductDBTypes, false, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}
	if err = randomize.Struct(seed, superProductTwo, superProductDBTypes, false, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = superProductOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = superProductTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SuperProducts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSuperProductsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	superProductOne := &SuperProduct{}
	superProductTwo := &SuperProduct{}
	if err = randomize.Struct(seed, superProductOne, superProductDBTypes, false, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}
	if err = randomize.Struct(seed, superProductTwo, superProductDBTypes, false, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = superProductOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = superProductTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func superProductBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func superProductAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperProduct) error {
	*o = SuperProduct{}
	return nil
}

func testSuperProductsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SuperProduct{}
	o := &SuperProduct{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, superProductDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SuperProduct object: %s", err)
	}

	AddSuperProductHook(boil.BeforeInsertHook, superProductBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	superProductBeforeInsertHooks = []SuperProductHook{}

	AddSuperProductHook(boil.AfterInsertHook, superProductAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	superProductAfterInsertHooks = []SuperProductHook{}

	AddSuperProductHook(boil.AfterSelectHook, superProductAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	superProductAfterSelectHooks = []SuperProductHook{}

	AddSuperProductHook(boil.BeforeUpdateHook, superProductBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	superProductBeforeUpdateHooks = []SuperProductHook{}

	AddSuperProductHook(boil.AfterUpdateHook, superProductAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	superProductAfterUpdateHooks = []SuperProductHook{}

	AddSuperProductHook(boil.BeforeDeleteHook, superProductBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	superProductBeforeDeleteHooks = []SuperProductHook{}

	AddSuperProductHook(boil.AfterDeleteHook, superProductAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	superProductAfterDeleteHooks = []SuperProductHook{}

	AddSuperProductHook(boil.BeforeUpsertHook, superProductBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	superProductBeforeUpsertHooks = []SuperProductHook{}

	AddSuperProductHook(boil.AfterUpsertHook, superProductAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	superProductAfterUpsertHooks = []SuperProductHook{}
}

func testSuperProductsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSuperProductsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(superProductColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSuperProductToManyProductCodeSuperProductDetails(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SuperProduct
	var b, c SuperProductDetail

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, superProductDetailDBTypes, false, superProductDetailColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, superProductDetailDBTypes, false, superProductDetailColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.ProductCode = a.ProductCode
	c.ProductCode = a.ProductCode

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.ProductCodeSuperProductDetails().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ProductCode == b.ProductCode {
			bFound = true
		}
		if v.ProductCode == c.ProductCode {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SuperProductSlice{&a}
	if err = a.L.LoadProductCodeSuperProductDetails(ctx, tx, false, (*[]*SuperProduct)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ProductCodeSuperProductDetails); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.ProductCodeSuperProductDetails = nil
	if err = a.L.LoadProductCodeSuperProductDetails(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ProductCodeSuperProductDetails); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSuperProductToManyAddOpProductCodeSuperProductDetails(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SuperProduct
	var b, c, d, e SuperProductDetail

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, superProductDBTypes, false, strmangle.SetComplement(superProductPrimaryKeyColumns, superProductColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*SuperProductDetail{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, superProductDetailDBTypes, false, strmangle.SetComplement(superProductDetailPrimaryKeyColumns, superProductDetailColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*SuperProductDetail{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddProductCodeSuperProductDetails(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ProductCode != first.ProductCode {
			t.Error("foreign key was wrong value", a.ProductCode, first.ProductCode)
		}
		if a.ProductCode != second.ProductCode {
			t.Error("foreign key was wrong value", a.ProductCode, second.ProductCode)
		}

		if first.R.ProductCodeSuperProduct != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.ProductCodeSuperProduct != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.ProductCodeSuperProductDetails[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.ProductCodeSuperProductDetails[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.ProductCodeSuperProductDetails().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSuperProductsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSuperProductsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SuperProductSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSuperProductsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SuperProducts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	superProductDBTypes = map[string]string{`Name`: `character varying`, `ProductCode`: `character varying`, `Price`: `bigint`, `ShopCode`: `character varying`, `URL`: `character varying`}
	_                   = bytes.MinRead
)

func testSuperProductsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(superProductPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(superProductAllColumns) == len(superProductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSuperProductsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(superProductAllColumns) == len(superProductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SuperProduct{}
	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, superProductDBTypes, true, superProductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(superProductAllColumns, superProductPrimaryKeyColumns) {
		fields = superProductAllColumns
	} else {
		fields = strmangle.SetComplement(
			superProductAllColumns,
			superProductPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SuperProductSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSuperProductsUpsert(t *testing.T) {
	t.Parallel()

	if len(superProductAllColumns) == len(superProductPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SuperProduct{}
	if err = randomize.Struct(seed, &o, superProductDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SuperProduct: %s", err)
	}

	count, err := SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, superProductDBTypes, false, superProductPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SuperProduct struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SuperProduct: %s", err)
	}

	count, err = SuperProducts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
