// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSuperShops(t *testing.T) {
	t.Parallel()

	query := SuperShops()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSuperShopsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSuperShopsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SuperShops().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSuperShopsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SuperShopSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSuperShopsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SuperShopExists(ctx, tx, o.ShopID)
	if err != nil {
		t.Errorf("Unable to check if SuperShop exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SuperShopExists to return true, but got false.")
	}
}

func testSuperShopsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	superShopFound, err := FindSuperShop(ctx, tx, o.ShopID)
	if err != nil {
		t.Error(err)
	}

	if superShopFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSuperShopsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SuperShops().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSuperShopsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SuperShops().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSuperShopsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	superShopOne := &SuperShop{}
	superShopTwo := &SuperShop{}
	if err = randomize.Struct(seed, superShopOne, superShopDBTypes, false, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}
	if err = randomize.Struct(seed, superShopTwo, superShopDBTypes, false, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = superShopOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = superShopTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SuperShops().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSuperShopsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	superShopOne := &SuperShop{}
	superShopTwo := &SuperShop{}
	if err = randomize.Struct(seed, superShopOne, superShopDBTypes, false, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}
	if err = randomize.Struct(seed, superShopTwo, superShopDBTypes, false, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = superShopOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = superShopTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func superShopBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func superShopAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SuperShop) error {
	*o = SuperShop{}
	return nil
}

func testSuperShopsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SuperShop{}
	o := &SuperShop{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, superShopDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SuperShop object: %s", err)
	}

	AddSuperShopHook(boil.BeforeInsertHook, superShopBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	superShopBeforeInsertHooks = []SuperShopHook{}

	AddSuperShopHook(boil.AfterInsertHook, superShopAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	superShopAfterInsertHooks = []SuperShopHook{}

	AddSuperShopHook(boil.AfterSelectHook, superShopAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	superShopAfterSelectHooks = []SuperShopHook{}

	AddSuperShopHook(boil.BeforeUpdateHook, superShopBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	superShopBeforeUpdateHooks = []SuperShopHook{}

	AddSuperShopHook(boil.AfterUpdateHook, superShopAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	superShopAfterUpdateHooks = []SuperShopHook{}

	AddSuperShopHook(boil.BeforeDeleteHook, superShopBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	superShopBeforeDeleteHooks = []SuperShopHook{}

	AddSuperShopHook(boil.AfterDeleteHook, superShopAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	superShopAfterDeleteHooks = []SuperShopHook{}

	AddSuperShopHook(boil.BeforeUpsertHook, superShopBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	superShopBeforeUpsertHooks = []SuperShopHook{}

	AddSuperShopHook(boil.AfterUpsertHook, superShopAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	superShopAfterUpsertHooks = []SuperShopHook{}
}

func testSuperShopsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSuperShopsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(superShopColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSuperShopsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSuperShopsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SuperShopSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSuperShopsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SuperShops().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	superShopDBTypes = map[string]string{`Name`: `character varying`, `ShopID`: `character varying`}
	_                = bytes.MinRead
)

func testSuperShopsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(superShopPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(superShopAllColumns) == len(superShopPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSuperShopsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(superShopAllColumns) == len(superShopPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SuperShop{}
	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, superShopDBTypes, true, superShopPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(superShopAllColumns, superShopPrimaryKeyColumns) {
		fields = superShopAllColumns
	} else {
		fields = strmangle.SetComplement(
			superShopAllColumns,
			superShopPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SuperShopSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSuperShopsUpsert(t *testing.T) {
	t.Parallel()

	if len(superShopAllColumns) == len(superShopPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SuperShop{}
	if err = randomize.Struct(seed, &o, superShopDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SuperShop: %s", err)
	}

	count, err := SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, superShopDBTypes, false, superShopPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SuperShop struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SuperShop: %s", err)
	}

	count, err = SuperShops().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
