services:
  front_dev:
    build:
      context: .
      dockerfile: ./services/front/Dockerfile.local
    container_name: front_dev
    restart: always
    ports:
     - 3000:3000
    tty: true
    stdin_open: true
    environment:
     - CHOKIDAR_USEPOLLING=true
     - REACT_APP_FQDN=http://localhost:5000
    entrypoint: npm run start
    volumes:
     - type: bind
       source: ./services/front/
       target: /app

  crawler_dev:
    build:
      context: .
      dockerfile: ./services/crawler/local.Dockerfile
    container_name: crawler_dev
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - DB_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-server:5432/${POSTGRES_DB}?sslmode=disable
      - TEST_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-server:5432/test?sslmode=disable
      - MQ_DSN=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:5672
      - HOST=crawler_dev
    entrypoint: tail -f /dev/null
    volumes: 
      - ./services/crawler:/go/src
      - go-pkg:/go/pkg
      - go-pkg:/go/bin

  api-server-dev:
    build:
      context: .
      dockerfile: ./services/api-server/Dockerfile.local
      args:
        APP_PATH: "services/api-server"
    container_name: api-server-dev
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - DB_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-server:5432/${POSTGRES_DB}?sslmode=disable
      - MQ_DSN=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:5672
      - TEST_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql-server:5432/test?sslmode=disable
      - SHOP_SERVICE_URL=http://crawler_dev:8080
      - SPAPI_SERVICE_URL=http://spapi-server-dev:8000
    entrypoint: air
    ports:
     - 5000:5000
    volumes:
      - ./services/api-server:/app
      - api-server-pkg:/go/pkg
      - api-server-pkg:/go/bin

  spapi-server-dev:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: spapi-server-dev
    environment:
      - TZ=Asia/Tokyo
    entrypoint: uvicorn server:app --reload --host spapi-server-dev
    ports:
      - 8000:8000
    working_dir: /app
    restart: always
    volumes: 
      - ./:/app

volumes:
  go-pkg:
  api-server-pkg:
  