version: "3.9"

services:
  front_dev:
    build:
      context: .
      dockerfile: ./services/front/Dockerfile.local
    container_name: front_dev
    restart: always
    ports:
     - 3000:3000
    tty: true
    stdin_open: true
    environment:
     - CHOKIDAR_USEPOLLING=true
    entrypoint: tail -f /dev/null
    volumes:
     - type: bind
       source: ./services/front/
       target: /app
  
  migrate_timescaledb_dev:
    build:
      context: .
      dockerfile: ./services/migrate_timescaledb/Dockerfile
    container_name: migrate_timescaledb_dev
    environment:
     - TZ=Asia/Tokyo
    entrypoint: tail -f /dev/null
    volumes:
     - ./services/migrate_timescaledb:/go/src
  