version: '3.9'

volumes:
  mongo_db_store:

services:
  mongo:
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fluentd
      MONGO_USERNAME: fluent
      MONGO_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo_db_store
        target: /data/db
      - type: volume
        source: mongo_db_store
        target: /data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  fluent:
    build:
      context: .
      dockerfile: ./docker/fluentd/Dockerfile
    container_name: fluentd
    ports:
      - 9880:9880
