output = "models"

[psql]
    dbname = "aps"
    host = "postgresql-server"
    port = "5432"
    user = "postgres"
    pass = "postgres"
    sslmode = "disable"
    blacklist = ["migrations", "other"]

[rabbitmq]
    user = "rabbitmq"
    pass = "rabbitmq"
    host = "rabbitmq"
    port = "5672"

[http]
    useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"